# Generated by Django 4.2.3 on 2023-08-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('word_length', models.IntegerField(default=0)),
                ('word_class', models.CharField(max_length=200)),
                ('definition', models.TextField()),
            ],
        ),
    ]
